# Configuracin del servidor
server.port=${SERVER_PORT:8080}

# Configuracin de la base de datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/curso_springboot}
spring.datasource.username=${DB_USERNAME:devdb}
spring.datasource.password=${DB_PASSWORD:a1b2c3d4}

# Configuracin de JPA (Java Persistence API)
spring.jpa.hibernate.ddl-auto=${JPA_DDL:create-drop}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Habilita la visualizacin de las consultas SQL en la consola.
spring.jpa.show-sql=${SHOW_SQL:true}

# Configuracin adicional
spring.application.name=facultad-service
api.version=v1

# Configuracin de la zona horaria y el idioma
spring.jackson.time-zone=${TIME_ZONE:America/Bogota}
spring.jackson.locale=${LOCALE:es_CO}

# Configuracin del tamao mximo de los archivos que se pueden subir
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:10MB}

# Configuracin del registro de depuracin (debug) de Spring y Hibernate
logging.level.web=${LOGGING_LEVEL_WEB:DEBUG}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_HIBERNATE_SQL:DEBUG}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOGGING_LEVEL_HIBERNATE_BINDER:debug}

# Exposicin de endpoints de operaciones
management.endpoints.web.exposure.include=${EXPOSED_ENDPOINTS:health}
